storage: /verdaccio/storage
plugins: /verdaccio/plugins

filters:
  plugin-daycare-filter:
    minWeeklyDownloads: 5000
    minAgeHours: 48

middlewares:
  plugin-daycare-middleware:
    minWeeklyDownloads: 5000
    minAgeHours: 48

auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1   # disable user signups completely

# Minimal uplinks and packages to proxy everything
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: false

packages:
  '**':
    access: $all     # allow everyone to fetch packages
    publish: none    # nobody can publish
    proxy: npmjs     # forward missing packages to npmjs

listen: 0.0.0.0:4873
